ACTION_NONE = 0
ACTION_CREATE = 1
ACTION_DELETE = 2
ACTION_CHANGE = 3
ACTION_NOEXSIST = 4
ACTION_CONFLICT = 5
ACTION_DUPLICATE = 6

SHARE_NONE = 0
SHARE_NEED_SHARE = 1
SHARE_SHARED = 2
SHARE_NEED_STOP = 3
