# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created: Sun Feb 24 18:32:37 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(565, 381)
        self.centralwidget = QtGui.QWidget(Editor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.contentView = QtWebKit.QWebView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentView.sizePolicy().hasHeightForWidth())
        self.contentView.setSizePolicy(sizePolicy)
        self.contentView.setUrl(QtCore.QUrl("about:blank"))
        self.contentView.setObjectName("contentView")
        self.horizontalLayout.addWidget(self.contentView)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.options = QtGui.QHBoxLayout()
        self.options.setObjectName("options")
        self.notebook = QtGui.QComboBox(self.centralwidget)
        self.notebook.setObjectName("notebook")
        self.options.addWidget(self.notebook)
        self.tags = QtGui.QLineEdit(self.centralwidget)
        self.tags.setObjectName("tags")
        self.options.addWidget(self.tags)
        self.verticalLayout.addLayout(self.options)
        self.resourceLabel = QtGui.QLabel(self.centralwidget)
        self.resourceLabel.setTextFormat(QtCore.Qt.AutoText)
        self.resourceLabel.setObjectName("resourceLabel")
        self.verticalLayout.addWidget(self.resourceLabel)
        self.alternativeVersions = QtGui.QLabel(self.centralwidget)
        self.alternativeVersions.setWordWrap(True)
        self.alternativeVersions.setObjectName("alternativeVersions")
        self.verticalLayout.addWidget(self.alternativeVersions)
        self.resourceArea = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resourceArea.sizePolicy().hasHeightForWidth())
        self.resourceArea.setSizePolicy(sizePolicy)
        self.resourceArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.resourceArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.resourceArea.setWidgetResizable(True)
        self.resourceArea.setObjectName("resourceArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 545, 76))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.resourceArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.resourceArea)
        Editor.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(Editor)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        Editor.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtGui.QMenuBar(Editor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 565, 25))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtGui.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        Editor.setMenuBar(self.menubar)
        self.actionSave = QtGui.QAction(Editor)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_and_close = QtGui.QAction(Editor)
        self.actionSave_and_close.setObjectName("actionSave_and_close")
        self.actionDelete = QtGui.QAction(Editor)
        self.actionDelete.setObjectName("actionDelete")
        self.actionClose = QtGui.QAction(Editor)
        self.actionClose.setObjectName("actionClose")
        self.actionCut = QtGui.QAction(Editor)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(Editor)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(Editor)
        self.actionPaste.setObjectName("actionPaste")
        self.actionFind = QtGui.QAction(Editor)
        self.actionFind.setObjectName("actionFind")
        self.menuFIle.addAction(self.actionSave)
        self.menuFIle.addAction(self.actionSave_and_close)
        self.menuFIle.addAction(self.actionDelete)
        self.menuFIle.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)

    def retranslateUi(self, Editor):
        Editor.setWindowTitle(QtGui.QApplication.translate("Editor", "Everpad", None, QtGui.QApplication.UnicodeUTF8))
        self.notebook.setToolTip(QtGui.QApplication.translate("Editor", "Select notebook", None, QtGui.QApplication.UnicodeUTF8))
        self.tags.setToolTip(QtGui.QApplication.translate("Editor", "Note tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tags.setPlaceholderText(QtGui.QApplication.translate("Editor", "Commas separated tags", None, QtGui.QApplication.UnicodeUTF8))
        self.resourceLabel.setText(QtGui.QApplication.translate("Editor", "%d attached files, <a href=\'#\'>show</a> / <a href=\'#\'> add another</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.alternativeVersions.setText(QtGui.QApplication.translate("Editor", "This note has alternative versions: %s", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("Editor", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFIle.setTitle(QtGui.QApplication.translate("Editor", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("Editor", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("Editor", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_and_close.setText(QtGui.QApplication.translate("Editor", "Save and close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("Editor", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("Editor", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("Editor", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("Editor", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("Editor", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setText(QtGui.QApplication.translate("Editor", "Find", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
